remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: [Cooking Up Success]
description: [In this project we determine if we can accurately predict the ratings of recipes based off the attributes of a recipe dataset. Continue reading for more. Thank you Suraj and TA's for a great quarter!]
